name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: kecci/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          template: markdown
          filename: metrics.markdown.md
          markdown: >-
            https://raw.githubusercontent.com/kecci/kecci/main/metrics.markdown.template.md
          config_output: markdown
          plugin_languages: yes
          plugin_languages_ignored: html, css, scss, cmake, shell
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_traffic: yes
          plugin_discussions: yes
          plugin_discussions_categories_limit: 8
          plugin_sponsors: yes
          plugin_achievements: no
          plugin_achievements_display: compact
          plugin_16personalities: yes
          plugin_16personalities_url: https://www.16personalities.com/profiles/ef6129e039ca0
          plugin_16personalities_sections: personality, profile, traits
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
          plugin_reactions: yes
          plugin_reactions_limit: 100
          plugin_reactions_details: percentage
